### ISSUE TITLE
Debian dependency package name changed: libmediainfo0

### ISSUE THREAD

**Issue by cparmar** [cmacrae/ansible-sonarr#1]
libmediainfo0 package is now called libmediainfo0v05.

**Comment by cmacrae** [comment]
Just did a successful Vagrant run and a successful run against an Ubuntu server I have running, both look like the `libmediainfo` package is still called `libmediainfo0`.

Which OS release is this on?

**Comment by bg-o** [comment]
Not sure about that, I got failure on Debian 8, package still called libmediainfo0.

```shell
TASK [sonarr : Ensure libmediainfo0v5 is installed] ****************************
fatal: [mrshokbox.duckdns.org]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'libmediainfo0v5' is available"}
	to retry, use: --limit @/Users/Boris/ansible/playbooks/sonarr.retry
```

**Comment by ytjohn** [comment]
On Ubuntu Xenial, this is now called libmediainfo0v5

What I did locally:

defaults/main.yml
```
sonarr_libmediainfo_package: libmediainfo0
```

tasks/Debian.yml
```
  - name: Ensure libmediainfo0 is installed
    package:
      name: "{{ sonarr_libmediainfo_package }}"
      state: present
```

Then set sonarr_libmediainfo_package in my group vars to `libmediainfo0v5`
